module.exports = module.exports = [
  {
    category: "hero",
    title: "Hero Images",
    description: "Images for the hero carousel",
    icon: "",
  },
  {
    category: "house-decoration",
    title: "House Decoration",
    description: "Transform your home for any occasion with beautiful and creative decorations.",
    icon: "🏠",
  },
  {
    category: "haldi-mehendi",
    title: "Haldi & Mehendi",
    description: "Traditional pre-wedding ceremonies with vibrant colors and joyful celebrations.",
    icon: "🌺",
  },
  {
    category: "flower-decoration",
    title: "Flower Decoration",
    description: "Romantic and elegant setups using flowers.",
    icon: "💐",
  },
  {
    category: "mandap-decoration",
    title: "Mandap Decoration",
    description: "Traditional and modern mandap setups for your perfect wedding ceremony.",
    icon: "🏵️",
  },
  {
    category: "bride-groom-entry",
    title: "Bride & Groom Entry",
    description: "Grand entrance setups that make your special moment unforgettable.",
    icon: "💒",
  },
  {
    category: "firework",
    title: "Firework Decoration",
    description: "Make your entry memorable using firework decoration.",
    icon: "🎆",
  },
  {
    category: "engagement-decoration",
    title: "Engagement Decoration",
    description: "Celebrate your engagement with elegant and joyful decorations.",
    icon: "💍",
  },
  {
    category: "baby-shower-decoration",
    title: "Baby Shower Decoration",
    description: "Beautiful and elegant setups to celebrate your love and milestones.",
    icon: "👶",
  },
  {
    category: "birthday-theme-decoration",
    title: "Birthday Theme Decoration",
    description: "Transform birthdays into extraordinary adventures with creative themes and vibrant decorations.",
    icon: "🎂",
  },
  {
    category: "anniversary-decoration",
    title: "Anniversary Decoration",
    description: "Romantic and elegant setups to celebrate your love and milestones.",
    icon: "💕",
  },
  {
    category: "naming-ceremony",
    title: "Naming Ceremony",
    description: "Celebrate your child's naming ceremony with beautiful decorations.",
    icon: "🍼",
  },
  {
    category: "car-decoration",
    title: "Car Decoration",
    description: "Decorate your car for weddings, birthdays, and special occasions.",
    icon: "🚗",
  },
  {
    category: "surprise-decoration",
    title: "Surprise Decoration",
    description: "Plan surprise parties with creative and fun decorations.",
    icon: "🎉",
  },
  {
    category: "room-decoration",
    title: "Room Decoration",
    description: "Transform any room into a celebration space.",
    icon: "🛏️",
  },
  {
    category: "annaprashan-decoration",
    title: "Annaprashan Decoration",
    description: "Celebrate your baby's first meal with traditional and festive decorations.",
    icon: "🍽️",
  },
  {
    category: "birthday-baby-entry",
    title: "Birthday Baby Entry",
    description: "Special entry setups for birthday babies.",
    icon: "👶",
  },
  {
    category: "welcome-baby-decoration",
    title: "Welcome Baby Decoration",
    description: "Welcome your newborn with adorable balloon decorations.",
    icon: "🎈",
  },
  {
    category: "baby-entry-decoration",
    title: "Baby Entry Decoration",
    description: "Special balloon setups for baby entry.",
    icon: "🎈",
  },
  {
    category: "haldi-mehendi-decoration",
    title: "Haldi & Mehendi Decoration",
    description: "Traditional Haldi & Mehendi setups for weddings.",
    icon: "🌼",
  },
  {
    category: "fireworks",
    title: "FireWorks",
    description: "Firework setups for wedding entries.",
    icon: "🎆",
  },
  {
    category: "stage-varmala-theme",
    title: "Stage Varmala Theme",
    description: "Special stage setups for varmala ceremonies.",
    icon: "🌹",
  },
  {
    category: "bride-welcome",
    title: "Bride Welcome Home",
    description: "Special decorations for welcoming the bride.",
    icon: "👰",
  },
];